-- AlterTable
ALTER TABLE "gor" ADD COLUMN "phone" TEXT;
ALTER TABLE "gor" ADD COLUMN "email" TEXT;
ALTER TABLE "gor" ADD COLUMN "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "gor" ADD COLUMN "province" TEXT NOT NULL DEFAULT '';
ALTER TABLE "gor" ADD COLUMN "logoUrl" TEXT;
ALTER TABLE "gor" ADD COLUMN "coverImageUrl" TEXT;
ALTER TABLE "gor" ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'Asia/Jakarta';
ALTER TABLE "gor" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'IDR';
ALTER TABLE "gor" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
