export const UI_COPY = {
  save: "Simpan",
  saving: "Menyimpan...",
  cancel: "Batal",
  edit: "Ubah",
  delete: "Hapus",
  deleting: "Menghapus...",
  confirmDelete: "Konfirmasi Hapus",
  view: "Lihat",
  active: "Aktif",
  inactive: "Tidak Aktif",
  activate: "Aktifkan",
  deactivate: "Nonaktifkan",
  court: "Lapangan",
  courts: "Lapangan",
  selectCourt: "Pilih lapangan",
  allCourts: "Semua lapangan",
  status: "Status",
  actions: "Aksi",
  loading: "Memuat...",
  previous: "Sebelumnya",
  next: "Berikutnya",
  refresh: "Muat Ulang",
  downloadPdf: "Unduh PDF",
  noData: "Belum ada data.",
  tryAgain: "Coba lagi",
  genericError: "Terjadi kesalahan. Silakan coba lagi.",
} as const;
