export const NOTIFICATION_TYPE = {
  BOOKING_CREATED: "BOOKING_CREATED",
  PAYMENT_AWAITING_CONFIRMATION: "PAYMENT_AWAITING_CONFIRMATION",
  PAYMENT_APPROVED: "PAYMENT_APPROVED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  SUBSCRIPTION_EXPIRING: "SUBSCRIPTION_EXPIRING",
  SUBSCRIPTION_ACTIVATED: "SUBSCRIPTION_ACTIVATED",
} as const;

export const NOTIFICATION_CATEGORY = {
  BOOKING: "BOOKING",
  PAYMENT: "PAYMENT",
  SYSTEM: "SYSTEM",
} as const;

export const NOTIFICATION_LIST_LIMIT = 50 as const;
export const NOTIFICATION_DROPDOWN_LIMIT = 8 as const;
export const SUBSCRIPTION_EXPIRING_REMINDER_DAYS = 7 as const;
export const SUBSCRIPTION_EXPIRING_DEDUP_HOURS = 24 as const;

export type NotificationFilter =
  "all" | "unread" | "booking" | "payment" | "system";
